# Gait polish: reward balanced leg use on all three remaining legs.

config = {
    "env_id": "DamageAnt-v0",
    "n_envs": 8,
    "total_timesteps": 1_500_000,
    "policy": "MlpPolicy",
    "learning_rate": 8e-6,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.06,
    "ent_coef": 0.006,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "fixed_disabled_legs": [1],
    "eval_fixed_disabled_legs": [1],
    "reset_noise_scale": 0.015,
    "tip_grace_steps": 160,
    "min_uprightness": 0.42,
    "forward_reward_weight": 3.0,
    "progress_reward_weight": 1.5,
    "forward_gate_uprightness": 0.62,
    "forward_gate_height": 0.40,
    "velocity_tracking_weight": 0.6,
    "target_speed": 0.16,
    "backward_penalty_weight": 0.28,
    "leg_balance_weight": 1.8,
    "upright_reward_weight": 2.5,
    "height_reward_weight": 1.5,
    "tilt_penalty_weight": 5.0,
    "ctrl_cost_weight": 0.12,
    "n_eval_episodes": 15,
    "early_stop_patience": 14,
    "pretrained_path": "checkpoints/damage/best_model/best_model",
}
