# Polish damage-robust policy: random single-leg amputation, stricter upright rewards.

config = {
    "env_id": "DamageAnt-v0",
    "n_envs": 8,
    "total_timesteps": 2_000_000,
    "policy": "MlpPolicy",
    "learning_rate": 5e-5,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.12,
    "ent_coef": 0.008,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "min_disabled_legs": 1,
    "max_disabled_legs": 1,
    "eval_fixed_disabled_legs": [1],
    "reset_noise_scale": 0.02,
    "forward_reward_weight": 1.5,
    "upright_reward_weight": 6.0,
    "height_reward_weight": 4.0,
    "tilt_penalty_weight": 5.0,
    "ctrl_cost_weight": 0.15,
    "n_eval_episodes": 15,
    "early_stop_patience": 15,
    "pretrained_path": "checkpoints/damage/best_model/best_model",
}
