# Upright polish only: stronger torso height/tilt, keep gait checkpoint speed recipe.

config = {
    "env_id": "DamageAnt-v0",
    "n_envs": 8,
    "total_timesteps": 600_000,
    "policy": "MlpPolicy",
    "learning_rate": 5e-6,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.04,
    "ent_coef": 0.005,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "fixed_disabled_legs": [1],
    "eval_fixed_disabled_legs": [1],
    "reset_noise_scale": 0.015,
    "tip_grace_steps": 170,
    "min_uprightness": 0.44,
    "forward_reward_weight": 2.8,
    "progress_reward_weight": 1.2,
    "forward_gate_uprightness": 0.64,
    "forward_gate_height": 0.42,
    "velocity_tracking_weight": 0.45,
    "target_speed": 0.14,
    "backward_penalty_weight": 0.28,
    "leg_balance_weight": 2.0,
    "upright_reward_weight": 4.0,
    "height_reward_weight": 3.0,
    "tilt_penalty_weight": 6.0,
    "ctrl_cost_weight": 0.12,
    "n_eval_episodes": 15,
    "early_stop_patience": 10,
    "pretrained_path": "checkpoints/damage/best_model/best_model",
}
