# Gentle holistic polish: gait checkpoint recipe + light foot/upright terms.

config = {
    "env_id": "DamageAnt-v0",
    "n_envs": 8,
    "total_timesteps": 1_000_000,
    "policy": "MlpPolicy",
    "learning_rate": 6e-6,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.05,
    "ent_coef": 0.006,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "fixed_disabled_legs": [1],
    "eval_fixed_disabled_legs": [1],
    "reset_noise_scale": 0.015,
    "tip_grace_steps": 170,
    "min_uprightness": 0.42,
    "forward_reward_weight": 3.0,
    "progress_reward_weight": 1.5,
    "forward_gate_uprightness": 0.62,
    "forward_gate_height": 0.40,
    "velocity_tracking_weight": 0.5,
    "target_speed": 0.15,
    "backward_penalty_weight": 0.28,
    "leg_balance_weight": 2.0,
    "foot_gait_weight": 0.35,
    "shuffle_penalty_weight": 0.6,
    "lateral_penalty_weight": 0.25,
    "min_leg_activity_weight": 0.4,
    "upright_reward_weight": 3.0,
    "height_reward_weight": 2.0,
    "tilt_penalty_weight": 5.0,
    "ctrl_cost_weight": 0.12,
    "n_eval_episodes": 15,
    "early_stop_patience": 12,
    "pretrained_path": "checkpoints/damage/best_model/best_model",
}
