# Short polish: fixed eval difficulty, very low LR, early stop — avoid overtraining drift.

config = {
    "env_id": "TerrainAnt-v0",
    "n_envs": 4,
    "total_timesteps": 1_000_000,
    "policy": "MlpPolicy",
    "learning_rate": 1e-5,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 8,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.05,
    "ent_coef": 0.001,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "difficulty": 0.4,
    "eval_difficulty": 0.4,
    "n_eval_episodes": 10,
    "forward_reward_weight": 2.0,
    "progress_reward_weight": 0.25,
    "ctrl_cost_weight": 0.45,
    "early_stop_patience": 8,
    "pretrained_path": "checkpoints/terrain/best_model/best_model",
}
