# Fine-tune flat policy for upright tripod gait with front-right leg always amputated.

config = {
    "env_id": "DamageAnt-v0",
    "n_envs": 8,
    "total_timesteps": 3_000_000,
    "policy": "MlpPolicy",
    "learning_rate": 1e-4,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.15,
    "ent_coef": 0.005,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "fixed_disabled_legs": [1],
    "eval_fixed_disabled_legs": [1],
    "forward_reward_weight": 2.0,
    "upright_reward_weight": 4.0,
    "height_reward_weight": 3.0,
    "tilt_penalty_weight": 3.0,
    "ctrl_cost_weight": 0.2,
    "n_eval_episodes": 10,
    "early_stop_patience": 12,
    "pretrained_path": "checkpoints/flat/best_model/best_model",
}
