# Balanced fine-tune: stable boost checkpoint + moderate forward reward, trained/evaluated at test difficulty.

config = {
    "env_id": "TerrainAnt-v0",
    "n_envs": 4,
    "total_timesteps": 3_000_000,
    "policy": "MlpPolicy",
    "learning_rate": 3e-5,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.08,
    "ent_coef": 0.003,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "difficulty": 0.4,
    "eval_difficulty": 0.4,
    "n_eval_episodes": 10,
    "forward_reward_weight": 2.0,
    "ctrl_cost_weight": 0.45,
    "pretrained_path": "results/ppo_terrainant_v0_1782867891/best_model/best_model",
}
