# Damage-robust training from scratch: always 1 random leg amputated, upright reward shaping.

config = {
    "env_id": "DamageAnt-v0",
    "n_envs": 8,
    "total_timesteps": 4_000_000,
    "policy": "MlpPolicy",
    "learning_rate": 3e-4,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.2,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "min_disabled_legs": 1,
    "max_disabled_legs": 1,
    "eval_fixed_disabled_legs": [1],
    "forward_reward_weight": 1.5,
    "upright_reward_weight": 2.5,
    "height_reward_weight": 2.0,
    "tilt_penalty_weight": 1.5,
    "ctrl_cost_weight": 0.25,
    "n_eval_episodes": 10,
    "early_stop_patience": 15,
}
