# Cross-leg speed polish: keep random single-leg amputation during training.

config = {
    "env_id": "DamageAnt-v0",
    "n_envs": 8,
    "total_timesteps": 3_000_000,
    "policy": "MlpPolicy",
    "learning_rate": 2e-5,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.1,
    "ent_coef": 0.005,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "min_disabled_legs": 1,
    "max_disabled_legs": 1,
    "reset_noise_scale": 0.02,
    "tip_grace_steps": 140,
    "min_uprightness": 0.40,
    "forward_reward_weight": 4.0,
    "progress_reward_weight": 3.0,
    "forward_gate_uprightness": 0.60,
    "forward_gate_height": 0.40,
    "velocity_tracking_weight": 2.5,
    "target_speed": 0.22,
    "backward_penalty_weight": 0.35,
    "upright_reward_weight": 1.5,
    "height_reward_weight": 1.0,
    "tilt_penalty_weight": 3.5,
    "ctrl_cost_weight": 0.08,
    "n_eval_episodes": 15,
    "early_stop_patience": 18,
}
