# Production damage-robust recipe (leg 1 amputation, upright gait).

config = {
    "env_id": "DamageAnt-v0",
    "n_envs": 8,
    "total_timesteps": 1_500_000,
    "policy": "MlpPolicy",
    "learning_rate": 3e-5,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.1,
    "ent_coef": 0.006,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "fixed_disabled_legs": [1],
    "eval_fixed_disabled_legs": [1],
    "reset_noise_scale": 0.02,
    "tip_grace_steps": 100,
    "forward_reward_weight": 2.0,
    "upright_reward_weight": 5.0,
    "height_reward_weight": 3.5,
    "tilt_penalty_weight": 4.0,
    "ctrl_cost_weight": 0.18,
    "n_eval_episodes": 15,
    "early_stop_patience": 12,
    "pretrained_path": "checkpoints/flat/best_model/best_model",
}
