# Gait-first fine-tune: foot alternation + anti-shuffle, minimal speed pressure.

config = {
    "env_id": "DamageAnt-v0",
    "n_envs": 8,
    "total_timesteps": 1_500_000,
    "policy": "MlpPolicy",
    "learning_rate": 5e-6,
    "n_steps": 2048,
    "batch_size": 256,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "clip_range": 0.05,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "seed": 42,
    "fixed_disabled_legs": [1],
    "eval_fixed_disabled_legs": [1],
    "reset_noise_scale": 0.012,
    "tip_grace_steps": 180,
    "min_uprightness": 0.44,
    "forward_reward_weight": 1.8,
    "progress_reward_weight": 0.6,
    "forward_gate_uprightness": 0.68,
    "forward_gate_height": 0.44,
    "velocity_tracking_weight": 0.0,
    "target_speed": 0.12,
    "backward_penalty_weight": 0.35,
    "leg_balance_weight": 3.0,
    "foot_gait_weight": 1.4,
    "shuffle_penalty_weight": 3.5,
    "lateral_penalty_weight": 0.8,
    "min_leg_activity_weight": 2.2,
    "upright_reward_weight": 4.0,
    "height_reward_weight": 3.0,
    "tilt_penalty_weight": 6.0,
    "ctrl_cost_weight": 0.15,
    "n_eval_episodes": 15,
    "early_stop_patience": 14,
    "pretrained_path": "checkpoints/damage/best_model/best_model",
}
